type FileItem = { id: string; relativePath: string; parentPath: string; name: string; isDirectory: boolean; mimeType: string | null; size: number; createdAt: string; modifiedAt: string; favorite: boolean; trashedAt: string | null; previewable?: boolean };
type View = 'drive' | 'recent' | 'favorites' | 'activity' | 'sync' | 'operations' | 'trash' | 'search';
type UploadPlan = { file: File; relativePath: string };
type UploadRecord = { localId: string; file: File; relativePath: string; parentPath: string; id?: string; progress: number; state: 'uploading' | 'error' | 'complete'; error?: string; controller?: AbortController };
const $ = <T extends HTMLElement = HTMLElement>(selector: string) => document.querySelector<T>(selector)!;
const state = { view: 'drive' as View, path: '', selected: new Set<string>(), items: [] as FileItem[], viewMode: (localStorage.getItem('cloud-view') ?? 'grid') as 'grid' | 'list', sort: 'name', direction: 'asc', uploads: [] as UploadRecord[], searchTimer: 0, syncRefreshTimer: 0, clipboard: null as { ids: string[]; mode: 'cut' | 'copy' } | null, searchFilters: {} as Record<string, string>, lastSearch: '', gallery: [] as FileItem[] };
const fileList = $('#file-list'); const loading = $('#loading'); const empty = $('#empty'); const details = $('#details'); const authDialog = $('#auth-dialog') as HTMLDialogElement; const previewDialog = $('#preview-dialog') as HTMLDialogElement;

class Api {
  private token(): string | null { return sessionStorage.getItem('continental-cloud-token'); }
  async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = new Headers(init.headers); const token = this.token(); if (token) headers.set('X-Continental-Token', token);
    const response = await fetch(`/api${path}`, { ...init, headers });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) throw Object.assign(new Error(body.error?.message ?? `Request failed (${response.status})`), { status: response.status, code: body.error?.code });
    return body.data as T;
  }
  json<T>(path: string, method = 'GET', body?: unknown): Promise<T> { return this.request<T>(path, body === undefined ? { method } : { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); }
  async download(path: string, body: unknown): Promise<Blob> {
    const headers = new Headers({ 'Content-Type': 'application/json' }); const token = this.token(); if (token) headers.set('X-Continental-Token', token);
    const response = await fetch(`/api${path}`, { method: 'POST', headers, body: JSON.stringify(body) });
    if (!response.ok) { const error = await response.json().catch(() => ({})); throw Object.assign(new Error(error.error?.message ?? `Download failed (${response.status})`), { status: response.status, code: error.error?.code }); }
    return response.blob();
  }
  async chunk<T>(path: string, data: Blob, signal: AbortSignal): Promise<T> { return this.request<T>(path, { method: 'PUT', headers: { 'Content-Type': 'application/octet-stream', 'Content-Length': String(data.size) }, body: data, signal }); }
}
const api = new Api();

function human(bytes: number | undefined | null): string { if (bytes === undefined || bytes === null || !Number.isFinite(bytes)) return '—'; if (bytes === 0) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const level = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024))); return `${(bytes / 1024 ** level).toFixed(level ? 1 : 0)} ${units[level]}`; }
function shortDate(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? '—' : new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: date.getFullYear() === new Date().getFullYear() ? undefined : 'numeric' }).format(date); }
function dateTime(value: string): string { const date = new Date(value); return Number.isNaN(date.valueOf()) ? '—' : new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date); }
function glyph(item: FileItem): string { if (item.isDirectory) return '▰'; if (item.mimeType?.startsWith('image/')) return '◉'; if (item.mimeType?.startsWith('video/')) return '▶'; if (item.mimeType?.startsWith('audio/')) return '♫'; if (item.mimeType === 'application/pdf') return '▤'; if (item.mimeType?.includes('json') || item.mimeType?.startsWith('text/')) return '‹›'; return '◇'; }
function isImage(item: FileItem): boolean { return Boolean(item.mimeType?.startsWith('image/') && item.mimeType !== 'image/svg+xml'); }
function toast(message: string, error = false, undo?: () => void): void { const node = document.createElement('div'); node.className = `toast${error ? ' error' : ''}`; const text = document.createElement('span'); text.textContent = message; node.append(text); if (undo) { const button = document.createElement('button'); button.className = 'quiet-button'; button.textContent = 'Undo'; button.addEventListener('click', () => { undo(); node.remove(); }); node.append(button); } $('#toasts').append(node); window.setTimeout(() => node.remove(), 7000); }

async function refresh(): Promise<void> {
  window.clearTimeout(state.syncRefreshTimer);
  loading.hidden = false; fileList.replaceChildren(); empty.hidden = true; state.selected.clear(); renderSelection(); renderDetails();
  try {
    if (state.view === 'drive') {
      const data = await api.request<{ path: string; items: FileItem[] }>(`/files?path=${encodeURIComponent(state.path)}&sort=${state.sort}&direction=${state.direction}`); state.items = data.items; renderBreadcrumbs();
    } else if (state.view === 'recent') { state.items = await api.request<FileItem[]>('/recent'); }
    else if (state.view === 'favorites') { state.items = await api.request<FileItem[]>('/favorites'); }
    else if (state.view === 'search') { /* items set by search */ }
    else if (state.view === 'trash') {
      const trash = await api.request<Array<{ id: string; originalPath: string; deletedAt: string; node: FileItem }>>('/trash');
      state.items = trash.map((entry) => ({ ...entry.node, id: entry.id, relativePath: entry.originalPath, modifiedAt: entry.deletedAt }));
    } else if (state.view === 'activity') { await renderActivity(); return; }
    else if (state.view === 'sync') { await renderSync(); return; }
    else if (state.view === 'operations') { await renderOperations(); return; }
    renderItems();
  } catch (error) { handleError(error); }
  finally { loading.hidden = true; }
}

function renderItems(): void {
  fileList.className = `file-grid ${state.viewMode === 'list' ? 'list' : ''}`; fileList.replaceChildren(); ($('#empty-sync-button') as HTMLElement).hidden = state.view !== 'drive';
  empty.hidden = state.items.length > 0 || state.view === 'activity';
  const fragment = document.createDocumentFragment();
  for (const item of state.items) fragment.append(renderCard(item));
  fileList.append(fragment); updateLabels();
}
function renderCard(item: FileItem): HTMLElement {
  const card = document.createElement('button'); card.type = 'button'; card.className = `file-card ${item.isDirectory ? 'folder' : ''}${state.selected.has(item.id) ? ' selected' : ''}`; card.dataset.id = item.id; card.dataset.modified = shortDate(item.modifiedAt); card.setAttribute('role', 'listitem');
  const thumb = document.createElement('span'); thumb.className = 'file-thumb';
  if (isImage(item)) { const image = document.createElement('img'); image.alt = ''; image.loading = 'lazy'; image.src = `/api/files/${item.id}/thumbnail`; image.onerror = () => { thumb.replaceChildren(glyphNode(item)); }; thumb.append(image); } else thumb.append(glyphNode(item));
  const name = document.createElement('span'); name.className = 'file-name'; name.textContent = item.name;
  const meta = document.createElement('span'); meta.className = 'file-meta'; meta.textContent = item.isDirectory ? 'Folder' : `${human(item.size)} · ${shortDate(item.modifiedAt)}`;
  card.append(thumb, name, meta);
  if (item.favorite) { const favorite = document.createElement('span'); favorite.className = 'file-favorite'; favorite.textContent = '✦'; card.append(favorite); }
  card.draggable = state.view !== 'trash'; card.addEventListener('dragstart', (event) => { if (!state.selected.has(item.id)) selectItem(item, event as unknown as MouseEvent); event.dataTransfer?.setData('application/x-continental-node', item.id); });
  if (item.isDirectory) { card.addEventListener('dragover', (event) => event.preventDefault()); card.addEventListener('drop', (event) => { event.preventDefault(); const id = event.dataTransfer?.getData('application/x-continental-node'); if (id) void moveNodes([id], item.relativePath); else if (event.dataTransfer) void uploadDropped(event.dataTransfer, item.relativePath); }); }
  card.addEventListener('click', (event) => selectItem(item, event));
  card.addEventListener('dblclick', () => openItem(item));
  card.addEventListener('keydown', (event) => { if (event.key === 'Enter') openItem(item); });
  return card;
}
function glyphNode(item: FileItem): HTMLElement { const value = document.createElement('span'); value.className = 'file-glyph'; value.textContent = glyph(item); return value; }
function selectItem(item: FileItem, event: MouseEvent): void { if (event.metaKey || event.ctrlKey) state.selected.has(item.id) ? state.selected.delete(item.id) : state.selected.add(item.id); else { state.selected.clear(); state.selected.add(item.id); } renderSelection(); renderItems(); renderDetails(); }
function openItem(item: FileItem): void { if (state.view === 'trash') { selectItem(item, new MouseEvent('click')); return; } if (item.isDirectory) { state.view = 'drive'; state.path = item.relativePath; refresh(); return; } preview(item); }
function renderSelection(): void { const actions = $('#selection-actions'); const count = state.selected.size; actions.hidden = !count || state.view === 'activity'; $('#selection-count').textContent = `${count} selected`; }
function selectedItems(): FileItem[] { return state.items.filter((item) => state.selected.has(item.id)); }

function renderBreadcrumbs(): void {
  const crumbs = $('#breadcrumbs'); crumbs.replaceChildren(); const root = crumb('My drive', ''); crumbs.append(root);
  let current = ''; for (const part of state.path.split('/').filter(Boolean)) { const sep = document.createElement('span'); sep.className = 'crumb-sep'; sep.textContent = '/'; crumbs.append(sep); current = current ? `${current}/${part}` : part; crumbs.append(crumb(part, current)); }
}
function crumb(label: string, path: string): HTMLButtonElement { const button = document.createElement('button'); button.className = 'crumb-button'; button.textContent = label; button.addEventListener('click', () => { state.view = 'drive'; state.path = path; refresh(); }); return button; }
function updateLabels(): void { const name: Record<View, string> = { drive: state.path ? state.path.split('/').at(-1)! : 'My drive', recent: 'Recent', favorites: 'Favorites', activity: 'Activity', sync: 'Folder sync', operations: 'Recovery & operations', trash: 'Trash', search: 'Search' }; $('#section-title').textContent = name[state.view]; $('#section-kicker').textContent = state.view === 'trash' ? 'RECOVERABLE DELETION' : state.view === 'search' ? 'SEARCH RESULTS' : state.view === 'sync' ? 'PRIVATE DEVICE SYNC' : state.view === 'operations' ? 'RECOVERY CENTER' : 'PRIVATE STORAGE'; ($('#search-tools') as HTMLElement).hidden = !['search', 'activity'].includes(state.view); document.querySelectorAll<HTMLButtonElement>('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.view === state.view)); }

function renderDetails(): void {
  details.replaceChildren(); const item = selectedItems()[0];
  if (!item) { const hint = document.createElement('div'); hint.className = 'details-empty'; hint.textContent = state.view === 'trash' ? 'Select an item to restore it or remove it permanently.' : 'Select a file to see its details.'; details.append(hint); return; }
  if (state.selected.size > 1) { const hint = document.createElement('div'); hint.className = 'details-empty'; hint.textContent = `${state.selected.size} items selected.`; details.append(hint); return; }
  if (isImage(item) && state.view !== 'trash') { const image = document.createElement('img'); image.className = 'details-preview'; image.alt = ''; image.src = `/api/files/${item.id}/thumbnail`; details.append(image); }
  const title = document.createElement('h2'); title.className = 'detail-name'; title.textContent = item.name; details.append(title);
  for (const [label, value] of [['Type', item.isDirectory ? 'Folder' : (item.mimeType ?? 'File')], ['Size', item.isDirectory ? '—' : human(item.size)], ['Modified', shortDate(item.modifiedAt)], ['Location', item.relativePath || 'My drive']]) { const row = document.createElement('div'); row.className = 'detail-row'; const key = document.createElement('span'); key.textContent = label; const field = document.createElement('b'); field.textContent = value; row.append(key, field); details.append(row); }
  const actions = document.createElement('div'); actions.className = 'detail-actions';
  if (state.view === 'trash') { actions.append(detailButton('Restore', () => restoreTrash(item.id)), detailButton('Delete permanently', () => deleteTrash(item.id))); }
  else { if (!item.isDirectory) actions.append(detailButton('Preview', () => preview(item)), detailButton('Download', () => download(item))); else actions.append(detailButton('Download archive', () => download(item)), detailButton('Set up sync', () => openSyncSetup(item.relativePath))); actions.append(detailButton(item.favorite ? 'Remove favorite' : 'Add to favorites', () => favoriteItems()), detailButton('Tags', () => assignTags(item))); if (!item.isDirectory) actions.append(detailButton('Version history', () => versions(item))); }
  details.append(actions);
}
function detailButton(label: string, action: () => void): HTMLButtonElement { const button = document.createElement('button'); button.textContent = label; button.addEventListener('click', action); return button; }
async function assignTags(item: FileItem): Promise<void> { try { const existing = await api.request<Array<{ name: string }>>(`/files/${item.id}/tags`); const value = prompt('Tags (comma-separated)', existing.map((tag) => tag.name).join(', ')); if (value === null) return; await api.request(`/files/${item.id}/tags`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tags: value.split(',').map((tag) => tag.trim()).filter(Boolean) }) }); toast('Tags updated.'); } catch (error) { handleError(error); } }

async function renderActivity(): Promise<void> { const events = await api.request<Array<{ id: string; action: string; nodeId: string | null; path: string | null; detail: string | null; createdAt: string }>>('/activity'); const query = (state.searchFilters.activity ?? '').toLowerCase(); state.items = []; fileList.className = 'file-grid list'; fileList.replaceChildren(); const filtered = events.filter((event) => !query || `${event.action} ${event.path ?? ''} ${event.detail ?? ''}`.toLowerCase().includes(query)); empty.hidden = filtered.length > 0; const tools = $('#search-tools'); tools.hidden = false; tools.replaceChildren(); const input = document.createElement('input'); input.placeholder = 'Filter action, device, file'; input.value = state.searchFilters.activity ?? ''; input.addEventListener('input', () => { state.searchFilters.activity = input.value; void renderActivity(); }); tools.append(input); for (const event of filtered) { const card = document.createElement('article'); card.className = 'file-card'; const title = document.createElement('span'); title.className = 'file-name'; title.textContent = event.action.replaceAll('_', ' '); const meta = document.createElement('span'); meta.className = 'file-meta'; meta.textContent = `${event.path ?? 'Cloud'} · ${shortDate(event.createdAt)}`; card.append(title, meta); if (event.nodeId) { const open = document.createElement('button'); open.className = 'quiet-button'; open.textContent = 'Open file'; open.addEventListener('click', async () => { try { const item = await api.request<FileItem>(`/files/${event.nodeId}`); openItem(item); } catch { toast('This item is no longer available.', true); } }); card.append(open); } fileList.append(card); } updateLabels(); loading.hidden = true; window.clearTimeout((renderActivity as any).liveTimer); (renderActivity as any).liveTimer = window.setTimeout(() => { if (state.view === 'activity') void renderActivity(); }, 15_000); }

type SyncProgressView = { initial: boolean; phase: string; filesDone: number; filesTotal: number; foldersDone: number; foldersTotal: number; bytesDone: number; bytesTotal: number; excludedFiles: number; excludedFolders: number };
type SyncMappingView = { id: string; cloudPath: string; localPath: string; policy: { preset: 'project' | 'exact'; exclude: string[] }; paused: boolean; status: string; lastError: string | null; progress: SyncProgressView | null };
type SyncDeviceView = { id: string; name: string; platform: string; clientVersion: string; lastSeenAt: string; revokedAt: string | null; mappings: SyncMappingView[] };
type PairingView = { id: string; code: string; cloudPath: string; expiresAt: string };
type InstallerPlatform = 'windows' | 'macos' | 'linux';
let pairingPoll: number | undefined;
let installerPoll: number | undefined;
let activePairing: PairingView | undefined;
function renderSyncWelcome(devices: SyncDeviceView[]): HTMLElement {
  const hasMappings = devices.some((device) => !device.revokedAt && device.mappings.length > 0);
  const section = document.createElement('section'); section.className = devices.length ? 'sync-summary sync-ready' : 'sync-welcome';
  const content = document.createElement('div'); const eyebrow = document.createElement('p'); eyebrow.className = 'eyebrow'; eyebrow.textContent = devices.length ? 'SYNC IS READY' : 'A SIMPLE WAY TO KEEP FOLDERS IN STEP'; const heading = document.createElement('h2'); heading.textContent = devices.length ? 'Your computers are connected' : 'Sync your folders, everywhere'; const folderCount = devices.reduce((count, device) => count + device.mappings.length, 0); const copy = document.createElement('p'); copy.textContent = devices.length ? `${devices.length} computer${devices.length === 1 ? '' : 's'} connected · ${folderCount} folder${folderCount === 1 ? '' : 's'} syncing. Add another computer or folder whenever you need it.` : 'Make a folder available on another computer without uploading it twice or managing complicated settings.'; content.append(eyebrow, heading, copy);
  if (!devices.length) {
    const steps = document.createElement('ol'); steps.className = 'sync-steps'; for (const [number, title, detail] of [['1', 'Choose the computer', 'Windows, macOS, and Linux are supported.'], ['2', 'Download one installer', 'The server prepares a small setup file with a one-time connection.'], ['3', 'Open it once', 'It chooses a safe default folder and starts sync automatically.']] as const) { const item = document.createElement('li'); const marker = document.createElement('span'); marker.textContent = number; const text = document.createElement('div'); const label = document.createElement('b'); label.textContent = title; const explanation = document.createElement('small'); explanation.textContent = detail; text.append(label, explanation); item.append(marker, text); steps.append(item); } content.append(steps);
  }
  const actions = document.createElement('div'); actions.className = 'sync-welcome-actions'; const setup = document.createElement('button'); setup.className = 'primary'; setup.textContent = devices.length ? 'Add another computer' : 'Download sync app'; setup.addEventListener('click', () => openSyncSetup()); actions.append(setup); const pair = document.createElement('button'); pair.className = 'quiet-button'; pair.textContent = 'Advanced pairing'; pair.addEventListener('click', () => openPairing()); actions.append(pair); if (hasMappings) { const help = document.createElement('button'); help.className = 'quiet-button'; help.textContent = 'Add a folder'; help.addEventListener('click', () => openMappingDialog(devices.find((device) => !device.revokedAt)?.id ?? '')); actions.append(help); } section.append(content, actions); return section;
}
function renderDeviceCard(device: SyncDeviceView): HTMLElement {
  const card = document.createElement('section'); card.className = `device-card${device.revokedAt ? ' device-revoked' : ''}`; const head = document.createElement('header'); const identity = document.createElement('div'); const title = document.createElement('h2'); title.textContent = device.name; const meta = document.createElement('p'); meta.textContent = `${platformLabel(device.platform)} · last seen ${shortDate(device.lastSeenAt)}`; identity.append(title, meta); head.append(identity);
  if (!device.revokedAt) { const revoke = document.createElement('button'); revoke.className = 'quiet-button danger'; revoke.textContent = 'Revoke'; revoke.addEventListener('click', async () => { if (!confirm(`Revoke ${device.name}? Its saved token will no longer authorize sync requests.`)) return; try { await api.request(`/sync/devices/${device.id}`, { method: 'DELETE' }); toast(`${device.name} was revoked.`); await refresh(); } catch (error) { handleError(error); } }); head.append(revoke); } else { const revoked = document.createElement('span'); revoked.className = 'sync-status error'; revoked.textContent = 'Revoked'; head.append(revoked); }
  const mappings = document.createElement('div'); mappings.className = 'mapping-list'; if (!device.mappings.length) { const none = document.createElement('div'); none.className = 'sync-mapping-empty'; const copy = document.createElement('p'); copy.textContent = 'No folders are connected on this computer yet.'; none.append(copy); if (!device.revokedAt) { const add = document.createElement('button'); add.className = 'quiet-button add-folder-button'; add.textContent = '＋ Choose a folder'; add.addEventListener('click', () => openMappingDialog(device.id)); none.append(add); } mappings.append(none); }
  for (const mapping of device.mappings) {
    const row = document.createElement('article'); row.className = 'mapping-row'; const paths = document.createElement('div'); const cloud = document.createElement('b'); cloud.textContent = mapping.cloudPath ? `/${mapping.cloudPath}` : 'My drive'; const local = document.createElement('small'); local.textContent = `↔ ${mapping.localPath} · ${mapping.policy.preset === 'project' ? 'Coding project profile' : 'Exact mirror'}`; paths.append(cloud, local); const controls = document.createElement('div'); controls.className = 'mapping-actions'; const status = document.createElement('span'); status.className = `sync-status ${mapping.paused ? 'paused' : mapping.status === 'error' || mapping.status === 'offline' || mapping.progress?.phase === 'error' ? 'error' : ''}`; status.textContent = syncStatusLabel(mapping.status, mapping.paused); const toggle = document.createElement('button'); toggle.className = 'quiet-button'; toggle.textContent = mapping.paused ? 'Resume' : 'Pause'; toggle.disabled = Boolean(device.revokedAt); toggle.addEventListener('click', () => void updateMapping(device.id, mapping.id, { paused: !mapping.paused })); const edit = document.createElement('button'); edit.className = 'quiet-button'; edit.textContent = 'Edit'; edit.disabled = Boolean(device.revokedAt); edit.addEventListener('click', () => openMappingDialog(device.id, mapping)); controls.append(status, toggle, edit); row.append(paths, controls); if (mapping.progress && mapping.progress.phase !== 'complete') { const progress = document.createElement('small'); progress.className = 'mapping-progress'; progress.textContent = syncProgressLabel(mapping.progress); row.append(progress); } if (mapping.progress && (mapping.progress.excludedFiles || mapping.progress.excludedFolders)) { const excluded = document.createElement('small'); excluded.className = 'mapping-progress'; const parts: string[] = []; if (mapping.progress.excludedFiles) parts.push(`${mapping.progress.excludedFiles} file${mapping.progress.excludedFiles === 1 ? '' : 's'}`); if (mapping.progress.excludedFolders) parts.push(`${mapping.progress.excludedFolders} folder${mapping.progress.excludedFolders === 1 ? '' : 's'}`); excluded.textContent = `${parts.join(' and ')} excluded by profile.`; row.append(excluded); } if (mapping.lastError) { const error = document.createElement('small'); error.className = 'mapping-error'; error.textContent = mapping.lastError; row.append(error); } mappings.append(row);
  }
  if (device.mappings.length && !device.revokedAt) { const add = document.createElement('button'); add.className = 'quiet-button add-folder-button'; add.textContent = '＋ Add another folder'; add.addEventListener('click', () => openMappingDialog(device.id)); mappings.append(add); }
  card.append(head, mappings); return card;
}
function platformLabel(platform: string): string { const value = platform.toLowerCase(); if (value.includes('darwin') || value.includes('mac')) return 'macOS'; if (value.includes('win')) return 'Windows'; if (value.includes('linux')) return 'Linux'; return platform; }
function syncStatusLabel(status: string, paused: boolean): string { if (paused) return 'Paused'; if (status === 'idle') return 'Synced'; if (status === 'syncing') return 'Syncing'; if (status === 'offline') return 'Offline'; if (status === 'error') return 'Needs attention'; return status || 'Waiting'; }
function syncProgressLabel(progress: SyncProgressView): string { const prefix = progress.initial ? 'Initial sync' : 'Syncing'; if (progress.phase === 'scanning') return `${prefix}: scanning local folder`; if (progress.bytesTotal) return `${prefix}: ${human(progress.bytesDone)} / ${human(progress.bytesTotal)} · ${progress.filesDone}/${progress.filesTotal} files`; return `${prefix}: ${progress.filesDone}/${progress.filesTotal} files · ${progress.foldersDone}/${progress.foldersTotal} folders`; }
function syncSetupCommand(): string { return `cloud-sync setup --server ${location.origin}`; }
async function renderSync(): Promise<void> {
  const [devices, activity] = await Promise.all([api.request<SyncDeviceView[]>('/sync/devices'), api.request<Array<{ action: string; path: string | null; detail: string | null; createdAt: string }>>('/activity?limit=100')]);
  state.items = []; fileList.className = 'sync-panel'; fileList.replaceChildren(); empty.hidden = true;
  fileList.append(renderSyncWelcome(devices));
  for (const device of devices) fileList.append(renderDeviceCard(device));
  const conflicts = activity.filter((event) => event.action === 'sync_conflict'); if (conflicts.length) { const card = document.createElement('section'); card.className = 'device-card conflicts-card'; const heading = document.createElement('h2'); heading.textContent = 'Conflicts are kept safe'; card.append(heading); const intro = document.createElement('p'); intro.textContent = 'Nothing was overwritten. Open the folder below to compare the copies and rename the one you want to keep.'; card.append(intro); for (const conflict of conflicts.slice(0, 8)) { const row = document.createElement('article'); row.className = 'conflict-choice'; const remote = document.createElement('div'); const remoteTitle = document.createElement('b'); remoteTitle.textContent = 'Cloud copy'; const remoteDetail = document.createElement('small'); remoteDetail.textContent = `${conflict.path ?? 'File'} · ${shortDate(conflict.createdAt)}`; remote.append(remoteTitle, remoteDetail); const local = document.createElement('div'); const title = document.createElement('b'); title.textContent = 'Second copy'; const detail = document.createElement('small'); detail.textContent = conflict.detail ?? 'Kept separately to avoid data loss'; const open = document.createElement('button'); open.className = 'quiet-button'; open.textContent = 'Open folder'; open.addEventListener('click', () => { toast('Both copies are preserved. Rename or move the second copy when you are ready.'); state.path = (conflict.path ?? '').split('/').slice(0, -1).join('/'); state.view = 'drive'; void refresh(); }); local.append(title, detail, open); row.append(remote, local); card.append(row); } fileList.append(card); }
  updateLabels(); loading.hidden = true; state.syncRefreshTimer = window.setTimeout(() => { if (state.view === 'sync') void renderSync(); }, 12_000);
}

function openSyncSetup(cloudPath = ''): void { window.clearInterval(installerPoll); installerPoll = undefined; ($('#sync-setup-command') as HTMLElement).textContent = syncSetupCommand(); ($('#sync-download-cloud') as HTMLInputElement).value = cloudPath; ($('#sync-download-status') as HTMLElement).hidden = true; document.querySelectorAll<HTMLButtonElement>('[data-installer-platform]').forEach((button) => { button.classList.toggle('primary', button.dataset.installerPlatform === detectedInstallerPlatform()); }); ($('#sync-setup-dialog') as HTMLDialogElement).showModal(); }
async function copySyncCommand(): Promise<void> { const command = syncSetupCommand(); try { await navigator.clipboard.writeText(command); toast('Setup command copied.'); } catch { const field = document.createElement('textarea'); field.value = command; field.setAttribute('readonly', ''); field.style.position = 'fixed'; field.style.opacity = '0'; document.body.append(field); field.select(); const copied = document.execCommand('copy'); field.remove(); toast(copied ? 'Setup command copied.' : command, !copied); } }
function detectedInstallerPlatform(): InstallerPlatform { const agent = navigator.userAgent.toLowerCase(); return agent.includes('windows') ? 'windows' : agent.includes('mac os') || agent.includes('macintosh') ? 'macos' : 'linux'; }
function installerLabel(platform: InstallerPlatform): string { return platform === 'windows' ? 'Windows' : platform === 'macos' ? 'macOS' : 'Linux'; }
async function downloadSyncInstaller(platform: InstallerPlatform): Promise<void> {
  const button = document.querySelector<HTMLButtonElement>(`[data-installer-platform="${platform}"]`); if (button) button.disabled = true;
  const status = $('#sync-download-status');
  try {
    const cloudPath = ($('#sync-download-cloud') as HTMLInputElement).value.trim(); const preset = ($('#sync-download-profile') as HTMLSelectElement).value === 'exact' ? 'exact' : 'project';
    const pairing = await api.json<PairingView>('/sync/pairing', 'POST', { cloudPath, policy: { preset } });
    const blob = await api.download('/sync/installer', { platform, code: pairing.code });
    const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = platform === 'windows' ? 'Continental Cloud Sync.cmd' : platform === 'macos' ? 'Continental Cloud Sync.zip' : 'continental-cloud-sync.sh'; document.body.append(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(anchor.href), 60_000);
    status.textContent = `Downloaded for ${installerLabel(platform)}. Open the file on that computer; it will ask where to keep the folder. This setup link expires ${dateTime(pairing.expiresAt)}.`; status.hidden = false;
    window.clearInterval(installerPoll); installerPoll = window.setInterval(() => { void checkInstallerPairing(pairing.id); }, 2500);
  } catch (error) { handleError(error); }
  finally { if (button) button.disabled = false; }
}
async function checkInstallerPairing(id: string): Promise<void> { try { const pairing = await api.request<PairingView & { state: 'pending' | 'claimed' | 'expired'; deviceId: string | null }>(`/sync/pairing/${id}`); const status = $('#sync-download-status'); if (pairing.state === 'claimed') { status.textContent = 'Computer connected. The first sync is running there now.'; toast('A computer joined folder sync.'); void refresh(); } else if (pairing.state === 'expired') status.textContent = 'This download link expired. Download a fresh installer to try again.'; if (pairing.state !== 'pending') { window.clearInterval(installerPoll); installerPoll = undefined; } } catch { /* status is non-essential while the setup dialog is open */ } }
async function downloadPairingInstaller(platform: InstallerPlatform): Promise<void> { if (!activePairing) return toast('Create a pairing code first.', true); const button = document.querySelector<HTMLButtonElement>(`[data-pairing-installer-platform="${platform}"]`); if (button) button.disabled = true; try { const blob = await api.download('/sync/installer', { platform, code: activePairing.code }); const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = platform === 'windows' ? 'Continental Cloud Sync.cmd' : platform === 'macos' ? 'Continental Cloud Sync.zip' : 'continental-cloud-sync.sh'; document.body.append(anchor); anchor.click(); anchor.remove(); window.setTimeout(() => URL.revokeObjectURL(anchor.href), 60_000); toast(`Installer downloaded for ${installerLabel(platform)}.`); } catch (error) { handleError(error); } finally { if (button) button.disabled = false; } }
function openPairing(cloudPath = ''): void { if (pairingPoll !== undefined) window.clearInterval(pairingPoll); window.clearInterval(installerPoll); installerPoll = undefined; activePairing = undefined; ($('#pair-cloud-path') as HTMLInputElement).value = cloudPath; ($('#pair-profile') as HTMLSelectElement).value = 'project'; ($('#pairing-result') as HTMLElement).hidden = true; ($('#pairing-token') as HTMLElement).textContent = ''; ($('#pairing-command') as HTMLElement).textContent = ''; ($('#pairing-status') as HTMLElement).textContent = 'Waiting for the device…'; ($('#sync-pairing-dialog') as HTMLDialogElement).showModal(); }
async function createPairing(): Promise<void> { const cloudPath = ($('#pair-cloud-path') as HTMLInputElement).value.trim(); const preset = ($('#pair-profile') as HTMLSelectElement).value === 'exact' ? 'exact' : 'project'; try { const pairing = await api.json<PairingView>('/sync/pairing', 'POST', { cloudPath, policy: { preset } }); activePairing = pairing; ($('#pairing-token') as HTMLElement).textContent = pairing.code; ($('#pairing-command') as HTMLElement).textContent = `cloud-sync pair --server ${location.origin} --code ${pairing.code} --local "<local-folder>"`; ($('#pairing-result') as HTMLElement).hidden = false; ($('#pairing-status') as HTMLElement).textContent = `Waiting for the device… expires ${dateTime(pairing.expiresAt)}.`; if (pairingPoll !== undefined) window.clearInterval(pairingPoll); pairingPoll = window.setInterval(() => { void checkPairing(pairing.id); }, 2500); } catch (error) { handleError(error); } }
async function checkPairing(id: string): Promise<void> { try { const pairing = await api.request<PairingView & { state: 'pending' | 'claimed' | 'expired'; deviceId: string | null }>(`/sync/pairing/${id}`); const status = $('#pairing-status'); status.textContent = pairing.state === 'claimed' ? 'Device claimed this code. You can close this window.' : pairing.state === 'expired' ? 'This code expired. Create another one.' : 'Waiting for the device…'; if (pairing.state !== 'pending' && pairingPoll !== undefined) { window.clearInterval(pairingPoll); pairingPoll = undefined; if (pairing.state === 'claimed') void refresh(); } } catch { /* the status is non-essential while the dialog is open */ } }
async function updateMapping(deviceId: string, mappingId: string, body: { paused?: boolean; status?: string }): Promise<void> { try { await api.json(`/sync/devices/${deviceId}/mappings/${mappingId}`, 'PATCH', body); toast(body.paused ? 'Folder sync paused.' : 'Folder sync resumed.'); await refresh(); } catch (error) { handleError(error); } }
function openMappingDialog(deviceId: string, mapping?: SyncMappingView): void { const dialog = $('#sync-mapping-dialog') as HTMLDialogElement; dialog.dataset.mappingPaused = String(Boolean(mapping?.paused)); ($('#sync-mapping-device') as HTMLInputElement).value = deviceId; ($('#sync-mapping-id') as HTMLInputElement).value = mapping?.id ?? ''; ($('#sync-mapping-cloud') as HTMLInputElement).value = mapping?.cloudPath ?? ''; ($('#sync-mapping-local') as HTMLInputElement).value = mapping?.localPath ?? '~/Continental Cloud'; $('#sync-mapping-eyebrow').textContent = mapping ? 'EDIT FOLDER' : 'ADD A FOLDER'; $('#sync-mapping-title').textContent = mapping ? 'Update this folder sync' : 'Choose folders to sync'; dialog.showModal(); }
async function saveMapping(): Promise<void> { const dialog = $('#sync-mapping-dialog') as HTMLDialogElement; const deviceId = ($('#sync-mapping-device') as HTMLInputElement).value; const mappingId = ($('#sync-mapping-id') as HTMLInputElement).value || crypto.randomUUID(); const cloudPath = ($('#sync-mapping-cloud') as HTMLInputElement).value.trim(); const localPath = ($('#sync-mapping-local') as HTMLInputElement).value.trim(); if (!deviceId || !localPath) return toast('Choose a local folder to continue.', true); try { await api.json(`/sync/devices/${deviceId}/mappings`, 'POST', { id: mappingId, cloudPath, localPath, ...(dialog.dataset.mappingPaused === 'true' ? { paused: true } : {}) }); dialog.close(); toast('Folder sync saved.'); await refresh(); } catch (error) { handleError(error); } }

async function renderOperations(): Promise<void> {
  const data = await api.request<{ storage: { freeBytes?: number; totalBytes?: number; usedBytes: number; breakdown: { managedBytes: number; trashBytes: number; versionBytes: number }; history: Array<{ freeBytes: number | null; totalBytes: number | null }> }; jobs: Array<{ kind: string; state: string; detail: string | null; createdAt: string }>; failedJobs: Array<{ kind: string; detail: string | null }>; uploads: unknown[]; usage: { folders: Array<{ folder: string; bytes: number }>; types: Array<{ type: string; bytes: number }> }; retention: { versionRetention: number; trashRetentionDays: number; trashItems: number; expiringTrash: number }; lastVerifiedRestore: { createdAt: string; path: string | null } | null }>('/operations');
  state.items = []; fileList.className = 'operations-panel'; fileList.replaceChildren(); empty.hidden = true;
  const card = (title: string): HTMLElement => { const node = document.createElement('section'); node.className = 'operation-card'; const heading = document.createElement('h2'); heading.textContent = title; node.append(heading); return node; };
  const health = card('Backup & storage health'); const last = document.createElement('p'); last.textContent = `Managed ${human(data.storage.usedBytes)} · free ${human(data.storage.freeBytes)} · last verified restore ${data.lastVerifiedRestore ? `${shortDate(data.lastVerifiedRestore.createdAt)}${data.lastVerifiedRestore.path ? ` (${data.lastVerifiedRestore.path})` : ''}` : 'not yet recorded'}`; const bars = document.createElement('div'); bars.className = 'health-bars'; for (const entry of data.storage.history.slice(0, 30).reverse()) { const bar = document.createElement('i'); bar.style.height = `${entry.freeBytes && entry.totalBytes ? Math.max(8, (entry.freeBytes / entry.totalBytes) * 100) : 8}%`; bars.append(bar); } health.append(last, bars);
  const jobs = card('Reconciliation & jobs'); for (const job of data.jobs.slice(0, 6)) { const row = document.createElement('div'); row.className = 'metric-row'; const label = document.createElement('span'); label.textContent = `${job.kind} · ${job.state}`; const date = document.createElement('b'); date.textContent = shortDate(job.createdAt); row.append(label, date); jobs.append(row); } const reconcile = document.createElement('button'); reconcile.className = 'quiet-button'; reconcile.textContent = 'Run reconciliation'; reconcile.addEventListener('click', async () => { try { const result = await api.json<{ indexed: number; removed: number }>('/storage/reconcile', 'POST', {}); toast(`Reconciled ${result.indexed} entries; removed ${result.removed} stale records.`); await refresh(); } catch (error) { handleError(error); } }); const cleanup = document.createElement('button'); cleanup.className = 'quiet-button'; cleanup.textContent = `Clean orphaned uploads (${data.uploads.length})`; cleanup.addEventListener('click', async () => { try { const result = await api.json<{ removedUploads: number; removedTrash: number }>('/operations/cleanup', 'POST', { includeTrash: false }); toast(`Removed ${result.removedUploads} abandoned uploads.`); await refresh(); } catch (error) { handleError(error); } }); jobs.append(reconcile, cleanup);
  const usage = card('Usage by folder and type'); for (const entry of data.usage.folders.slice(0, 4)) { const row = document.createElement('div'); row.className = 'metric-row'; const label = document.createElement('span'); label.textContent = entry.folder; const value = document.createElement('b'); value.textContent = human(entry.bytes); row.append(label, value); usage.append(row); } for (const entry of data.usage.types.slice(0, 4)) { const row = document.createElement('div'); row.className = 'metric-row'; const label = document.createElement('span'); label.textContent = entry.type; const value = document.createElement('b'); value.textContent = human(entry.bytes); row.append(label, value); usage.append(row); }
  const retention = card('Retention simulator'); const policy = document.createElement('p'); policy.textContent = `${data.retention.trashItems} items in Trash; ${data.retention.expiringTrash} will expire within 7 days. Keep ${data.retention.versionRetention} versions and Trash for ${data.retention.trashRetentionDays} days.`; const versions = document.createElement('input'); versions.type = 'number'; versions.min = '1'; versions.max = '1000'; versions.value = String(data.retention.versionRetention); const days = document.createElement('input'); days.type = 'number'; days.min = '1'; days.max = '3650'; days.value = String(data.retention.trashRetentionDays); const save = document.createElement('button'); save.className = 'quiet-button'; save.textContent = 'Apply retention rules'; save.addEventListener('click', async () => { try { await api.json('/operations/retention', 'PATCH', { versionRetention: Number(versions.value), trashRetentionDays: Number(days.value) }); toast('Retention rules updated.'); await refresh(); } catch (error) { handleError(error); } }); retention.append(policy, versions, days, save);
  for (const node of [health, jobs, usage, retention]) fileList.append(node); updateLabels(); loading.hidden = true;
}

async function preview(item: FileItem): Promise<void> {
  const host = $('#preview-content'); host.replaceChildren(); const content = `/api/files/${item.id}/content`;
  try {
    if (item.mimeType?.startsWith('image/')) { state.gallery = state.items.filter(isImage); const element = document.createElement('img'); element.src = content; element.alt = item.name; host.append(element); const nav = document.createElement('div'); nav.className = 'preview-actions'; const index = state.gallery.findIndex((entry) => entry.id === item.id); for (const [label, direction] of [['← Previous', -1], ['Next →', 1]] as const) { const button = document.createElement('button'); button.className = 'quiet-button'; button.textContent = label; button.disabled = index + direction < 0 || index + direction >= state.gallery.length; button.addEventListener('click', () => void preview(state.gallery[index + direction])); nav.append(button); } host.append(nav); }
    else if (item.mimeType?.startsWith('video/')) { const element = document.createElement('video'); element.src = content; element.controls = true; element.autoplay = true; host.append(element); }
    else if (item.mimeType?.startsWith('audio/')) { const element = document.createElement('audio'); element.src = content; element.controls = true; element.autoplay = true; host.append(element); }
    else if (item.mimeType === 'application/pdf') { const frame = document.createElement('iframe'); frame.src = content; frame.title = item.name; const pages = document.createElement('div'); pages.className = 'preview-actions'; for (let page = 1; page <= 6; page++) { const link = document.createElement('a'); link.className = 'quiet-button'; link.textContent = `Page ${page}`; link.href = `${content}#page=${page}`; link.target = 'pdf-preview'; link.addEventListener('click', () => { frame.src = `${content}#page=${page}`; }); pages.append(link); } host.append(frame, pages); }
    else if (item.mimeType?.startsWith('text/') || item.mimeType?.includes('json')) { const result = await fetch(content, { headers: tokenHeader() }); if (!result.ok) throw new Error('Could not read preview.'); const text = await result.text(); const textHost = document.createElement('pre'); textHost.textContent = text.slice(0, 1_000_000) + (text.length > 1_000_000 ? '\n\n[Preview limited to 1 MB]' : ''); const actions = document.createElement('div'); actions.className = 'preview-actions'; if (item.mimeType?.includes('markdown')) { const rendered = document.createElement('article'); rendered.className = 'markdown-preview'; for (const line of text.split('\n').slice(0, 1000)) { const node = document.createElement(line.startsWith('# ') ? 'h2' : line.startsWith('## ') ? 'h3' : 'p'); node.textContent = line.replace(/^#{1,2}\s*/, ''); rendered.append(node); } actions.append(detailButton('Rendered Markdown', () => { host.replaceChildren(rendered, actions); })); } const edit = document.createElement('button'); edit.className = 'quiet-button'; edit.textContent = 'Edit and save version'; edit.addEventListener('click', () => editTextFile(item, text)); actions.append(edit); host.append(textHost, actions); }
    else { toast('A preview is not available for this file.'); return; }
    previewDialog.showModal();
  } catch (error) { handleError(error); }
}
async function editTextFile(item: FileItem, content: string): Promise<void> { const host = $('#preview-content'); host.replaceChildren(); const editor = document.createElement('textarea'); editor.value = content; editor.style.width = '100%'; editor.style.height = '100%'; const save = document.createElement('button'); save.className = 'primary'; save.textContent = 'Save new version'; save.addEventListener('click', async () => { try { const file = new File([editor.value], item.name, { type: item.mimeType ?? 'text/plain' }); await uploadFilesAt(toUploadPlans([file], false), item.parentPath, true); previewDialog.close(); toast('Saving a new version…'); } catch (error) { handleError(error); } }); host.append(editor, save); }
function tokenHeader(): HeadersInit { const token = sessionStorage.getItem('continental-cloud-token'); return token ? { 'X-Continental-Token': token } : {}; }
function download(item: FileItem): void { const anchor = document.createElement('a'); anchor.href = `/api/files/${item.id}/${item.isDirectory ? 'archive' : 'download'}`; anchor.download = item.isDirectory ? `${item.name}.tar` : item.name; document.body.append(anchor); anchor.click(); anchor.remove(); }

async function uploadFiles(files: FileList | File[], replace = false): Promise<void> {
  return uploadFilesAt(toUploadPlans(files, false), state.path, replace);
}
async function uploadFolder(files: FileList | File[]): Promise<void> {
  return uploadFilesAt(toUploadPlans(files, true), state.path, false);
}
async function uploadFilesAt(plans: UploadPlan[], parentPath: string, replace = false): Promise<void> {
  if (!plans.length) return toast('That folder did not contain any files.', true);
  try {
    const safePlans = plans.map((plan) => ({ ...plan, relativePath: normalizeUploadPath(plan.relativePath) }));
    await ensureUploadFolders(safePlans, parentPath);
    for (const plan of safePlans) {
      const record: UploadRecord = { localId: crypto.randomUUID(), file: plan.file, relativePath: plan.relativePath, parentPath: uploadJoin(parentPath, uploadParent(plan.relativePath)), progress: 0, state: 'uploading' };
      state.uploads.push(record); renderUploads(); void uploadFile(record, replace);
    }
    toast(`${safePlans.length} file${safePlans.length === 1 ? '' : 's'} queued from the folder.`);
  } catch (error) { handleError(error); }
}
function toUploadPlans(files: FileList | File[], preservePaths: boolean): UploadPlan[] {
  return Array.from(files).map((file) => ({ file, relativePath: preservePaths ? ((file as File & { webkitRelativePath?: string }).webkitRelativePath || file.name) : file.name }));
}
async function ensureUploadFolders(plans: UploadPlan[], rootPath: string): Promise<void> {
  const folders = new Set<string>();
  for (const plan of plans) { const parts = plan.relativePath.split('/').slice(0, -1); for (let index = 1; index <= parts.length; index++) folders.add(parts.slice(0, index).join('/')); }
  for (const folder of [...folders].sort((left, right) => left.split('/').length - right.split('/').length)) {
    const parentPath = uploadJoin(rootPath, uploadParent(folder)); const name = folder.split('/').at(-1)!;
    const listing = await api.request<{ items: FileItem[] }>(`/files?path=${encodeURIComponent(parentPath)}`); const existing = listing.items.find((item) => item.name === name);
    if (existing) { if (!existing.isDirectory) throw new Error(`Cannot create folder ${folder}: a file already has that name.`); } else await api.json('/files/folder', 'POST', { parentPath, name });
  }
}
function normalizeUploadPath(value: string): string {
  const parts = value.replaceAll('\\', '/').split('/').filter(Boolean);
  if (!parts.length || parts.some((part) => part === '.' || part === '..' || part.includes('\0'))) throw new Error(`Unsafe folder entry: ${value}`);
  return parts.join('/');
}
function uploadParent(path: string): string { const index = path.lastIndexOf('/'); return index === -1 ? '' : path.slice(0, index); }
function uploadJoin(left: string, right: string): string { return [left, right].filter(Boolean).join('/'); }
type BrowserFileEntry = { isFile: boolean; isDirectory: boolean; name: string; file?: (success: (file: File) => void, error?: () => void) => void; createReader?: () => BrowserDirectoryReader };
type BrowserDirectoryReader = { readEntries: (success: (entries: BrowserFileEntry[]) => void, error?: () => void) => void };
async function uploadDropped(dataTransfer: DataTransfer, parentPath: string): Promise<void> {
  try { const plans = await droppedPlans(dataTransfer); await uploadFilesAt(plans, parentPath); } catch (error) { handleError(error); }
}
async function droppedPlans(dataTransfer: DataTransfer): Promise<UploadPlan[]> {
  const entries: BrowserFileEntry[] = [];
  for (const item of Array.from(dataTransfer.items ?? [])) {
    const itemWithEntry = item as unknown as { webkitGetAsEntry?: () => BrowserFileEntry | null };
    const entry = itemWithEntry.webkitGetAsEntry?.();
    if (entry) entries.push(entry);
  }
  if (entries.length) return (await Promise.all(entries.map((entry) => walkDropEntry(entry)))).flat();
  return toUploadPlans(dataTransfer.files, true);
}
async function walkDropEntry(entry: BrowserFileEntry, prefix = ''): Promise<UploadPlan[]> {
  const path = prefix ? `${prefix}/${entry.name}` : entry.name;
  if (entry.isFile && entry.file) return [{ file: await new Promise<File>((resolve, reject) => entry.file!(resolve, reject)), relativePath: path }];
  if (!entry.isDirectory || !entry.createReader) return [];
  const children: BrowserFileEntry[] = []; const reader = entry.createReader();
  for (;;) { const batch = await new Promise<BrowserFileEntry[]>((resolve, reject) => reader.readEntries(resolve, reject)); if (!batch.length) break; children.push(...batch); }
  return (await Promise.all(children.map((child) => walkDropEntry(child, path)))).flat();
}
async function uploadFile(record: UploadRecord, replace: boolean, parentPath = state.path): Promise<void> {
  try {
    const session = await api.json<{ id: string; chunkSize: number; chunkCount: number }>('/uploads', 'POST', { parentPath: record.parentPath || parentPath, name: record.file.name, size: record.file.size, mimeType: record.file.type || undefined, overwrite: replace }); record.id = session.id;
    for (let index = 0; index < session.chunkCount; index++) { const controller = new AbortController(); record.controller = controller; const start = index * session.chunkSize; await api.chunk(`/uploads/${session.id}/chunks/${index}`, record.file.slice(start, Math.min(record.file.size, start + session.chunkSize)), controller.signal); record.progress = (index + 1) / session.chunkCount; renderUploads(); }
    await api.json(`/uploads/${session.id}/complete`, 'POST', {}); record.state = 'complete'; record.progress = 1; toast(`${record.relativePath} is in your cloud.`); await refresh();
  } catch (error: any) {
    if (error.name === 'AbortError') { record.state = 'error'; record.error = 'Cancelled'; } else if (error.status === 409 && !replace && confirm(`“${record.relativePath}” already exists. Replace it and preserve a version?`)) { record.state = 'uploading'; record.progress = 0; renderUploads(); await uploadFile(record, true, parentPath); return; } else { record.state = 'error'; record.error = error.message ?? 'Upload failed'; }
    toast(`${record.relativePath}: ${record.error}`, true);
  } finally { renderUploads(); if (record.state === 'complete') window.setTimeout(() => { state.uploads = state.uploads.filter((item) => item !== record); renderUploads(); }, 1800); }
}
function renderUploads(): void { const dock = $('#upload-dock'); dock.replaceChildren(); dock.hidden = state.uploads.length === 0; for (const record of state.uploads) { const row = document.createElement('div'); row.className = 'upload-item'; const name = document.createElement('b'); name.textContent = record.relativePath; const button = document.createElement('button'); button.textContent = record.state === 'uploading' ? 'Cancel' : record.state === 'error' ? 'Retry' : 'Done'; button.disabled = record.state === 'complete'; button.addEventListener('click', () => { if (record.state === 'uploading') { record.controller?.abort(); if (record.id) api.request(`/uploads/${record.id}`, { method: 'DELETE' }).catch(() => undefined); } else if (record.state === 'error') { record.state = 'uploading'; record.progress = 0; record.error = undefined; void uploadFile(record, false); renderUploads(); } }); const status = document.createElement('span'); status.className = 'upload-status'; status.textContent = record.state === 'error' ? record.error ?? 'Failed' : `${Math.round(record.progress * 100)}%`; const track = document.createElement('div'); track.className = 'upload-progress'; const bar = document.createElement('i'); bar.style.width = `${record.progress * 100}%`; track.append(bar); row.append(name, button, status, track); dock.append(row); } }

async function favoriteItems(): Promise<void> { for (const item of selectedItems()) { const operation = { method: 'PATCH' as const, path: `/files/${item.id}`, body: { action: 'favorite', favorite: !item.favorite }, label: 'favorite change' }; if (!navigator.onLine) queueOffline(operation); else await api.json(operation.path, operation.method, operation.body); } if (navigator.onLine) await refresh(); }
function setClipboard(mode: 'cut' | 'copy'): void { const ids = [...state.selected]; if (!ids.length) return; state.clipboard = { ids, mode }; toast(`${ids.length} item${ids.length === 1 ? '' : 's'} ${mode === 'cut' ? 'ready to move' : 'copied'}.`); }
async function moveNodes(ids: string[], parentPath: string): Promise<void> { try { for (const id of ids) await api.json(`/files/${id}`, 'PATCH', { action: 'move', parentPath }); toast(`${ids.length} item${ids.length === 1 ? '' : 's'} moved.`); await refresh(); } catch (error) { handleError(error); } }
async function pasteClipboard(): Promise<void> { if (!state.clipboard) return toast('Copy or cut files first.', true); const { ids, mode } = state.clipboard; try { for (const id of ids) await api.json(`/files/${id}`, 'PATCH', { action: mode === 'cut' ? 'move' : 'copy', parentPath: state.path }); if (mode === 'cut') state.clipboard = null; toast(`${ids.length} item${ids.length === 1 ? '' : 's'} ${mode === 'cut' ? 'moved' : 'copied'}.`); await refresh(); } catch (error) { handleError(error); } }
function downloadItems(): void { for (const item of selectedItems()) download(item); }
async function duplicateItems(): Promise<void> { const items = selectedItems(); try { for (const item of items) await api.json(`/files/${item.id}`, 'PATCH', { action: 'copy', parentPath: item.parentPath }); await refresh(); toast(`${items.length} duplicate${items.length === 1 ? '' : 's'} created.`); } catch (error) { handleError(error); } }
async function actionItems(action: 'rename' | 'move' | 'copy' | 'delete' | 'restore'): Promise<void> { const items = selectedItems(); if (!items.length) return; if (state.view === 'trash') { if (action === 'restore' || action === 'delete') try { const result = await api.json<{ restored?: number; deleted?: number }>('/trash/bulk', 'POST', { action, ids: items.map((item) => item.id) }); toast(action === 'restore' ? `${result.restored} item${items.length === 1 ? '' : 's'} restored.` : `${result.deleted} item${items.length === 1 ? '' : 's'} permanently deleted.`); await refresh(); } catch (error) { handleError(error); } return; } if (action === 'restore') return; try { if (action === 'delete') { if (!confirm(`Move ${items.length} item${items.length === 1 ? '' : 's'} to Trash?`)) return; const trashIds: string[] = []; for (const item of items) { if (!navigator.onLine) return toast('Trash needs a server connection.', true); const result = await api.request<{ trashId: string }>(`/files/${item.id}`, { method: 'DELETE' }); trashIds.push(result.trashId); } toast(`${items.length} item${items.length === 1 ? '' : 's'} moved to Trash.`, false, () => void Promise.all(trashIds.map((id) => api.json(`/trash/${id}/restore`, 'POST', {}))).then(() => { toast('Restored.'); return refresh(); }).catch(handleError)); } else if (action === 'rename') { if (items.length !== 1) return toast('Choose one item to rename.', true); const name = prompt('New name', items[0].name); if (!name) return; const operation = { method: 'PATCH' as const, path: `/files/${items[0].id}`, body: { action, name }, label: 'rename' }; if (!navigator.onLine) queueOffline(operation); else await api.json(operation.path, operation.method, operation.body); } else { const destination = prompt(`${action === 'move' ? 'Move' : 'Copy'} into folder path (blank is My drive)`, ''); if (destination === null) return; for (const item of items) { const operation = { method: 'PATCH' as const, path: `/files/${item.id}`, body: { action, parentPath: destination }, label: `${action} change` }; if (!navigator.onLine && action === 'move') queueOffline(operation); else if (!navigator.onLine) return toast('Copy needs a server connection.', true); else await api.json(operation.path, operation.method, operation.body); } } if (navigator.onLine) await refresh(); } catch (error) { handleError(error); } }
async function restoreTrash(id: string): Promise<void> { try { await api.json(`/trash/${id}/restore`, 'POST', {}); toast('Restored to your drive.'); await refresh(); } catch (error) { handleError(error); } }
async function deleteTrash(id: string): Promise<void> { if (!confirm('Permanently delete this item? This cannot be undone.')) return; try { await api.request(`/trash/${id}`, { method: 'DELETE' }); toast('Permanently deleted.'); await refresh(); } catch (error) { handleError(error); } }
async function versions(item: FileItem): Promise<void> { try { const list = await api.request<Array<{ id: string; size: number; createdAt: string; mimeType?: string | null }>>(`/files/${item.id}/versions`); if (!list.length) return toast('No earlier versions yet.'); const host = $('#versions-content'); host.replaceChildren(); const layout = document.createElement('div'); layout.className = 'versions-layout'; const timeline = document.createElement('div'); timeline.className = 'version-timeline'; const previewHost = document.createElement('div'); previewHost.className = 'version-preview'; const show = async (version: typeof list[number], button?: HTMLButtonElement) => { timeline.querySelectorAll('.version-row').forEach((row) => row.classList.remove('active')); button?.classList.add('active'); previewHost.replaceChildren(); const result = await fetch(`/api/versions/${version.id}/content`, { headers: tokenHeader() }); if (!result.ok) throw new Error('Could not load that version.'); const text = await result.text(); const code = document.createElement('pre'); code.textContent = text.slice(0, 1_000_000); const actions = document.createElement('div'); actions.className = 'preview-actions'; const downloadVersion = document.createElement('a'); downloadVersion.className = 'quiet-button'; downloadVersion.href = `/api/versions/${version.id}/content`; downloadVersion.textContent = 'Download'; const overwrite = document.createElement('button'); overwrite.className = 'quiet-button'; overwrite.textContent = 'Restore current file'; overwrite.addEventListener('click', async () => { await api.json(`/versions/${version.id}/restore`, 'POST', {}); toast('Version restored; the previous current file is preserved.'); ($('#versions-dialog') as HTMLDialogElement).close(); await refresh(); }); const copy = document.createElement('button'); copy.className = 'quiet-button'; copy.textContent = 'Restore as new copy'; copy.addEventListener('click', async () => { const restored = await api.json<FileItem>(`/versions/${version.id}/restore-copy`, 'POST', {}); toast(`Restored ${restored.name} as a separate copy.`); await refresh(); }); actions.append(downloadVersion, copy, overwrite); previewHost.append(code, actions); }; for (const version of list) { const row = document.createElement('button'); row.className = 'version-row'; row.textContent = `${shortDate(version.createdAt)} · ${human(version.size)}`; row.addEventListener('click', () => void show(version, row)); timeline.append(row); } layout.append(timeline, previewHost); host.append(layout); ($('#versions-dialog') as HTMLDialogElement).showModal(); await show(list[0], timeline.firstElementChild as HTMLButtonElement); } catch (error) { handleError(error); } }

function handleError(error: any): void { if (error?.status === 401) { authDialog.showModal(); return; } toast(error?.message ?? 'Something went wrong.', true); }
function renderSearchTools(): void { const host = $('#search-tools'); host.replaceChildren(); const field = (label: string, name: string, type = 'text'): HTMLInputElement => { const wrap = document.createElement('label'); wrap.textContent = label; const input = document.createElement('input'); input.type = type; input.name = name; input.value = state.searchFilters[name] ?? ''; input.addEventListener('change', () => { state.searchFilters[name] = input.value; void runSearch(state.lastSearch); }); wrap.append(input); host.append(wrap); return input; }; const type = document.createElement('label'); type.textContent = 'Type'; const select = document.createElement('select'); select.innerHTML = '<option value="">Any</option><option value="image">Image</option><option value="text">Text/code</option><option value="application/pdf">PDF</option>'; select.value = state.searchFilters.type ?? ''; select.addEventListener('change', () => { state.searchFilters.type = select.value; void runSearch(state.lastSearch); }); type.append(select); host.append(type); field('Folder', 'path'); field('Min size', 'minSize', 'number'); field('Max size', 'maxSize', 'number'); field('After', 'after', 'date'); field('Before', 'before', 'date'); const duplicates = document.createElement('button'); duplicates.className = 'quiet-button'; duplicates.textContent = 'Find duplicates'; duplicates.addEventListener('click', () => void showDuplicates()); const saved = document.createElement('button'); saved.className = 'quiet-button'; saved.textContent = 'Save search'; saved.addEventListener('click', async () => { const name = prompt('Name this saved search'); if (!name) return; try { await api.json('/saved-searches', 'POST', { name, query: state.lastSearch, filters: state.searchFilters }); toast('Saved search added.'); } catch (error) { handleError(error); } }); host.append(duplicates, saved); }
async function runSearch(query: string): Promise<void> { state.lastSearch = query; state.view = 'search'; const params = new URLSearchParams({ q: query }); for (const [key, value] of Object.entries(state.searchFilters)) if (value) params.set(key, value); try { state.items = await api.request<FileItem[]>(`/search?${params}`); renderSearchTools(); renderItems(); } catch (error) { handleError(error); } }
async function showDuplicates(): Promise<void> { try { const groups = await api.request<Array<{ checksum: string; count: number; bytes: number; items: FileItem[] }>>('/duplicates'); state.items = groups.flatMap((group) => group.items); state.view = 'search'; renderSearchTools(); renderItems(); toast(groups.length ? `${groups.length} duplicate groups found.` : 'No duplicates with matching content were found.'); } catch (error) { handleError(error); } }
async function updateSuggestions(query: string): Promise<void> { if (!query) return; try { const list = await api.request<string[]>(`/search/suggestions?q=${encodeURIComponent(query)}`); const host = $('#search-suggestions') as HTMLDataListElement; host.replaceChildren(...list.map((value) => { const option = document.createElement('option'); option.value = value; return option; })); } catch { /* suggestions are non-essential */ } }
type OfflineOperation = { method: 'POST' | 'PATCH'; path: string; body: unknown; label: string };
function offlineOperations(): OfflineOperation[] { try { return JSON.parse(localStorage.getItem('continental-offline-operations') ?? '[]') as OfflineOperation[]; } catch { return []; } }
function queueOffline(operation: OfflineOperation): void { const queue = offlineOperations(); queue.push(operation); localStorage.setItem('continental-offline-operations', JSON.stringify(queue.slice(-100))); toast(`${operation.label} queued until you are online.`); }
async function flushOfflineQueue(): Promise<void> { if (!navigator.onLine) return; const queue = offlineOperations(); if (!queue.length) return; const remaining: OfflineOperation[] = []; for (const operation of queue) { try { await api.json(operation.path, operation.method, operation.body); } catch (error: any) { if (error?.status === 401) { remaining.push(operation); break; } toast(`Could not apply queued ${operation.label}: ${error?.message ?? 'unknown error'}`, true); } } localStorage.setItem('continental-offline-operations', JSON.stringify(remaining)); if (!remaining.length) { toast(`${queue.length} queued change${queue.length === 1 ? '' : 's'} applied.`); await refresh(); } }
async function checkHealth(): Promise<void> { try { const health = await api.request<{ state: string; storage: { freeBytes?: number; totalBytes?: number; detail?: string }; version: string }>('/health'); const storage = await api.request<{ usedBytes: number | null; freeBytes?: number; totalBytes?: number; state: string }>('/storage'); const ready = health.state === 'ready'; $('#connection-label').textContent = ready ? 'Storage online' : health.storage.detail ?? 'Storage offline'; $('#connection-dot').parentElement!.className = `connection ${ready ? 'ready' : 'offline'}`; $('#storage-label').textContent = storage.totalBytes ? `${human(storage.usedBytes)} used` : 'Unavailable'; ($('#storage-meter') as HTMLElement).style.width = storage.totalBytes && storage.usedBytes !== null ? `${Math.min(100, (storage.usedBytes / storage.totalBytes) * 100)}%` : '0%'; } catch (error) { if ((error as any).status === 401) authDialog.showModal(); else { $('#connection-label').textContent = 'Storage unavailable'; $('#connection-dot').parentElement!.className = 'connection offline'; } } }

function bindEvents(): void {
  document.addEventListener('click', (event) => { const button = (event.target as Element).closest<HTMLElement>('[data-action]'); if (!button) return; const action = button.dataset.action; if (action === 'new') ($('#new-dialog') as HTMLDialogElement).showModal(); if (action === 'open-sync') { state.view = 'sync'; state.path = ''; void refresh(); } if (action === 'mobile-nav') $('.sidebar').classList.toggle('open'); if (action === 'theme') { document.documentElement.classList.toggle('light'); localStorage.setItem('cloud-theme', document.documentElement.classList.contains('light') ? 'light' : 'dark'); } if (action === 'grid' || action === 'list') { state.viewMode = action; localStorage.setItem('cloud-view', action); refresh(); } if (action === 'sort') { state.sort = state.sort === 'name' ? 'modified' : state.sort === 'modified' ? 'size' : 'name'; state.direction = state.sort === 'name' ? 'asc' : 'desc'; $('#sort-button').textContent = `${state.sort[0].toUpperCase()}${state.sort.slice(1)} ↕`; refresh(); } if (action === 'favorite') void favoriteItems(); if (action === 'download') downloadItems(); if (action === 'cut') setClipboard('cut'); if (action === 'copy-clipboard') setClipboard('copy'); if (action === 'paste') void pasteClipboard(); if (action === 'duplicate') void duplicateItems(); if (['rename', 'move', 'copy', 'delete', 'restore'].includes(action ?? '')) void actionItems(action as 'rename' | 'move' | 'copy' | 'delete' | 'restore'); if (action === 'close-preview') previewDialog.close(); if (action === 'copy-sync-command') void copySyncCommand(); if (action === 'download-sync-installer' && (button.dataset.platform === 'windows' || button.dataset.platform === 'macos' || button.dataset.platform === 'linux')) void downloadSyncInstaller(button.dataset.platform); if (action === 'close-sync-setup') { window.clearInterval(installerPoll); installerPoll = undefined; ($('#sync-setup-dialog') as HTMLDialogElement).close(); } if (action === 'refresh-sync') { window.clearInterval(installerPoll); installerPoll = undefined; ($('#sync-setup-dialog') as HTMLDialogElement).close(); toast('Looking for your computer…'); void refresh(); } if (action === 'close-sync-mapping') ($('#sync-mapping-dialog') as HTMLDialogElement).close(); });
  document.addEventListener('keydown', (event) => { const target = event.target as HTMLElement; if (target.matches('input,textarea,[contenteditable=true]')) return; if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'a') { event.preventDefault(); state.items.forEach((item) => state.selected.add(item.id)); renderSelection(); renderItems(); renderDetails(); } else if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'c') { event.preventDefault(); setClipboard('copy'); } else if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'x') { event.preventDefault(); setClipboard('cut'); } else if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'v') { event.preventDefault(); void pasteClipboard(); } else if (event.key === 'Delete' || event.key === 'Backspace') { if (state.selected.size) { event.preventDefault(); void actionItems('delete'); } } else if (event.key === 'Enter' && state.selected.size === 1) openItem(selectedItems()[0]); else if (event.key === 'Escape') { state.selected.clear(); renderSelection(); renderItems(); renderDetails(); } });
  document.querySelectorAll<HTMLButtonElement>('.nav-item').forEach((button) => button.addEventListener('click', () => { state.view = button.dataset.view as View; state.path = ''; state.selected.clear(); $('.sidebar').classList.remove('open'); refresh(); }));
  document.querySelectorAll<HTMLElement>('[data-new-choice]').forEach((button) => button.addEventListener('click', async (event) => { event.preventDefault(); ($('#new-dialog') as HTMLDialogElement).close(); if (button.dataset.newChoice === 'files') $('#file-input').click(); else if (button.dataset.newChoice === 'folder-upload') $('#folder-input').click(); else { const name = prompt('Name your folder'); if (!name) return; try { const operation = { method: 'POST' as const, path: '/files/folder', body: { parentPath: state.path, name }, label: 'new folder' }; if (!navigator.onLine) queueOffline(operation); else { await api.json(operation.path, operation.method, operation.body); await refresh(); } } catch (error) { handleError(error); } } }));
  $('#file-input').addEventListener('change', (event) => { const input = event.target as HTMLInputElement; if (input.files?.length) void uploadFiles(input.files); input.value = ''; });
  $('#folder-input').addEventListener('change', (event) => { const input = event.target as HTMLInputElement; if (input.files?.length) void uploadFolder(input.files); input.value = ''; });
  const dropzone = $('#dropzone'); for (const kind of ['dragenter', 'dragover']) dropzone.addEventListener(kind, (event) => { event.preventDefault(); dropzone.classList.add('dragging'); }); for (const kind of ['dragleave', 'drop']) dropzone.addEventListener(kind, (event) => { event.preventDefault(); dropzone.classList.remove('dragging'); }); dropzone.addEventListener('drop', (event) => { const dataTransfer = (event as DragEvent).dataTransfer; if (dataTransfer) void uploadDropped(dataTransfer, state.path); });
  $('#search').addEventListener('input', (event) => { const query = (event.target as HTMLInputElement).value.trim(); window.clearTimeout(state.searchTimer); state.searchTimer = window.setTimeout(async () => { if (!query) { state.view = 'drive'; await refresh(); return; } void updateSuggestions(query); await runSearch(query); }, 240); });
  window.addEventListener('online', () => { toast('Back online. Syncing queued changes…'); void flushOfflineQueue(); }); window.addEventListener('offline', () => toast('Offline: supported file actions will be queued.'));
  document.addEventListener('keydown', (event) => { if (previewDialog.open && state.gallery.length && (event.key === 'ArrowLeft' || event.key === 'ArrowRight')) { const image = state.gallery.find((entry) => `/api/files/${entry.id}/content` === (document.querySelector('#preview-content img') as HTMLImageElement | null)?.src.replace(location.origin, '')); const index = image ? state.gallery.indexOf(image) : -1; const next = state.gallery[index + (event.key === 'ArrowLeft' ? -1 : 1)]; if (next) { event.preventDefault(); void preview(next); } } });
  document.addEventListener('click', (event) => { const button = (event.target as Element).closest<HTMLElement>('[data-action]'); const action = button?.dataset.action; if (action === 'create-pairing') void createPairing(); if (action === 'download-pairing-installer' && (button?.dataset.platform === 'windows' || button?.dataset.platform === 'macos' || button?.dataset.platform === 'linux')) void downloadPairingInstaller(button.dataset.platform); if (action === 'copy-pairing-command') { const command = ($('#pairing-command') as HTMLElement).textContent ?? ''; const copy = navigator.clipboard?.writeText(command); if (copy) copy.then(() => toast('Setup command copied.')).catch(() => toast('Copy the setup command manually.', true)); else toast('Copy the setup command manually.', true); } if (action === 'close-sync-pairing') { if (pairingPoll !== undefined) { window.clearInterval(pairingPoll); pairingPoll = undefined; } ($('#sync-pairing-dialog') as HTMLDialogElement).close(); } if (action === 'close-versions') ($('#versions-dialog') as HTMLDialogElement).close(); });
  ($('#sync-mapping-form') as HTMLFormElement).addEventListener('submit', (event) => { event.preventDefault(); void saveMapping(); });
  ($('#auth-form') as HTMLFormElement).addEventListener('submit', async (event) => { event.preventDefault(); const token = ($('#token-input') as HTMLInputElement).value; sessionStorage.setItem('continental-cloud-token', token); try { await api.json('/session', 'POST', {}); sessionStorage.removeItem('continental-cloud-token'); await checkHealth(); authDialog.close(); ($('#auth-error') as HTMLElement).hidden = true; await flushOfflineQueue(); await refresh(); } catch { sessionStorage.removeItem('continental-cloud-token'); const error = $('#auth-error'); error.textContent = 'Could not authenticate with that token.'; error.hidden = false; } });
}

if (localStorage.getItem('cloud-theme') === 'light') document.documentElement.classList.add('light');
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined);
bindEvents(); void checkHealth().then(refresh);
